// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kedqjvbjhgawezupepzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlZHFqdmJqaGdhd2V6dXBlcHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzkwMTUsImV4cCI6MjA2NTA1NTAxNX0.i11vHAvEy-amAbuJi73yzhvIGy0fp51ooPF2iubOerA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);